a,b=input().split()
a=int(a)
b=int(b)
c,d,e,f,g=input().split()
c=int(c)
d=int(d)
e=int(e)
f=int(f)
g=int(g)
print(str(c-(a*b)) + " " + str(d-(a*b)) + " " + str(e-(a*b)) + " " + str(f-(a*b)) + " " + str(g-(a*b)))
